- README.md
- index.md
Fixed a lot of broken links within the table of contents and added
missing entries.
> Fixed many broken links.

- README.md
Brain.fm is an excelent platform that uses IA to tailor sounds to help you relax/focus.
> Added brain.fm to Pacifier section

- README.md
- contributing.md
- index.md
meanwhile fixed a lot of typos, added new items and removed non-valid items
> Added More Descriptions

- README.md
- index.md
I made some minor improvements in Git, Pomodoro and GTD sections. I believe it could be useful to other people.
Thank you,
Gustavo Bittencourt
> Minor improvements in Git, Pomodoro and GTD sections.

- README.md
http://shiny.chemgrid.org/boxplotr/
I put this in the most appropriate place I could think of. If there's a better place to put it on the list, let me know.
> Add BoxPlotR to R data visualization tools

- README.md
More of a book rather than a tool. But still probably valuable to a researcher in general.
> Add On Being a Scientist book

- index.md
I just stumbled upon your great list and wanted to add [JabRef](https://github.com/JabRef/jabref)
Many greetings from the JabRef Dev Team.
> Add JabRef as Bibliography manager

- README.md
Another aggregator of various research tools.
Source: http://dirtdirectory.org/
> Add DiRT Directory to More Section

- README.md
Source: http://www.mapinseconds.com/
> Add MapInSeconds.com to create map and data images

- README.md
Yet another color chooser application, but with a simple interface.
> Add Color Calculator

- README.md
Add a link to Awesome OSINT, which provides resources to search for papers.
I did not want to duplicate that list, but provide a link. Therefore, I sorted it into a category, even though the category might not be 100% fitting.
> Add link to Awesome OSINT

- README.md
fixed the self-plagiarism link because someone changed the wiki page titles
> Update link and fix a couple typos

- README.md
A couple suggestions that I thought would suit well in your list. 
I also had in mind: 
- academicons https://jpswalsh.github.io/academicons/
- orcid http://orcid.org/
But I was unsure this would fit in this list. Anyway, many thanks for sharing this.
> remark, Maple, Rust and 3 useful links to manage references

- README.md
All the tools I've recommended I have used and they are all very powerful and cool to use. I just recently came across the Publish or Perish tool (great name for the tool), which is an incredible desktop tool to do literature reviews and citation analysis.
> Add reference tools and small fixes

- README.md
Signed-off-by: Jack Yu <jackyu1996@hotmail.com>
> Update Taskade supported platforms

- README.md
Here are some cool tools I've run into recently that help in some way to check your writing. Not a replacement for actually reading as you write, but another set of eyes can't hurt :smirk:
> Add various writing tools

- README.md
It's easier to read and more correct this way.
> Improve writing in the Self-plagiarism section

- README.md
https://www.connectedpapers.com/ is super useful in the short time I've used it! 
Edit: https://github.com/emptymalei/awesome-research/issues/52#issuecomment-966098776 I found this, Im happy to maintain this project is you'd like, some work needs to be done in making it fit the awesome guidelines which I was about to tackle 😆, Im glad I didnt before I saw the comment haha
> Added connected papers

- README.md
Their repo states: "This project is no longer being maintained"
> Remove FlyLaTeX as it is no longer maintained (last updated 2016)

- README.md
Cleaned up a couple of dead links and replaced where I could find
> fix: Update dead links
